### ISSUE TITLE
Crash in Android API 28

### ISSUE THREAD

**Issue by alexrainman** [VideoSpike/nativescript-web-image-cache#62]
OS: Android API 28
Device: Emulator
NativeScript: 5.0
Angular 6.0

StackTrace

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

TypeError: Cannot read property 'ScalingUtils' of undefined
File: "file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js, line: 12, column: 47

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js', line: 12, column: 48
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/web-image-cache.js', line: 4, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.component.js', line: 4, column: 38
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.module.js', line: 6, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'ScalingUtils' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js', line: 12, column: 48
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/web-image-cache.js', line: 4, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.component.js', line: 4, column: 38
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.module.js', line: 6, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'ScalingUtils' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js', line: 12, column: 48
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/web-image-cache.js', line: 4, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.component.js', line: 4, column: 38
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.module.js', line: 6, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'ScalingUtils' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js', line: 12, column: 48
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/web-image-cache.js', line: 4, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.component.js', line: 4, column: 38
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.module.js', line: 6, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'ScalingUtils' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js', line: 12, column: 48
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/web-image-cache.js', line: 4, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.component.js', line: 4, column: 38
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.module.js', line: 6, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'ScalingUtils' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js', line: 12, column: 48
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/web-image-cache.js', line: 4, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.component.js', line: 4, column: 38
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.module.js', line: 6, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

TypeError: Cannot read property 'ScalingUtils' of undefined
File: "file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js, line: 12, column: 47

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js', line: 12, column: 48
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/web-image-cache.js', line: 4, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.component.js', line: 4, column: 38
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.module.js', line: 6, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'ScalingUtils' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js', line: 12, column: 48
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/web-image-cache.js', line: 4, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.component.js', line: 4, column: 38
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.module.js', line: 6, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'ScalingUtils' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js', line: 12, column: 48
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/web-image-cache.js', line: 4, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.component.js', line: 4, column: 38
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.module.js', line: 6, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'ScalingUtils' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js', line: 12, column: 48
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/web-image-cache.js', line: 4, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.component.js', line: 4, column: 38
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.module.js', line: 6, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'ScalingUtils' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js', line: 12, column: 48
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/web-image-cache.js', line: 4, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.component.js', line: 4, column: 38
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.module.js', line: 6, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'ScalingUtils' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/and-ts-lib/stretch-mapping.js', line: 12, column: 48
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/tns_modules/nativescript-web-image-cache/web-image-cache.js', line: 4, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.component.js', line: 4, column: 38
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/app/app.module.js', line: 6, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.LDAPSearch/files/app/main.js', line: 5, column: 20
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:553)
	at com.tns.Runtime.run(Runtime.java:545)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
	... 8 more
```

**Comment by anaszgh** [comment]
I have the same issue

TNS version 4.3.2 - Angular

**Comment by Omi231** [comment]
@alexrainman @anaszgh  You guys found any solution?
